name: Build bindings for Alpine releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
          - 19
          - 20

    steps:
      - name: Install Alpine build tools
        run: apk add --no-cache python3 make git gcc g++ bash

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install packages
        run: npm install --unsafe-perm
        env:
          SKIP_RDKAFKA_BINARY_DOWNLOAD_FOR_CI: true

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v3
        if: github.repository_owner == 'qiujie8092916' && github.event_name != 'pull_request'
        with:
          name: ${{ matrix.node }}
          path: vendor/
