name: Build bindings for Alpine releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
          - 19
          - 20

    steps:
      - name: Install Alpine build tools
        run: apk add --no-cache python3 make git gcc g++ bash

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install packages
        run: npm install --unsafe-perm

      - name: Run configure
        run: npm run configure

      - name: Run install
        run: npm run install

      - name: Run tests
        run: npm test

      - name: Run package
        run: npm run package

      - name: Run publish
        run: NODE_PRE_GYP_GITHUB_TOKEN=${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }} && npm run publish
