name: Build bindings for Linux releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - node: 16
            gcc: "gcc-8"
            gpp: "g++-8"
            os: ubuntu-20.04
          - node: 18
            gcc: "gcc-8"
            gpp: "g++-8"
            os: ubuntu-20.04
          - node: 19
            gcc: "gcc-8"
            gpp: "g++-8"
            os: ubuntu-20.04
          - node: 20
            gcc: "gcc-10"
            gpp: "g++-10"
            os: ubuntu-22.04


    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup GCC/G++
        run: sudo apt-get install ${{ matrix.gcc }} ${{ matrix.gpp }}

      - name: Install packages
        run: npm install --unsafe-perm

      - name: Run configure
        run: npm run configure

      - name: Run install
        run: npm run install

      - name: Run tests
        run: npm test

      - name: Run package
        run: npm run package

      - name: Run publish
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: npm run publish
