name: Build bindings for macOS releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
          - 19
          - 20

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install packages
        run: npm install --unsafe-perm

      - name: Run configure
        run: npm run configure

      - name: Run install
        run: npm run install

      - name: Run tests
        run: npm test

      - name: Run package
        run: npm run package

      - name: Run publish
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: npm run publish
