name: Build bindings for Windows releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
          - 19
          - 20

        architecture:
          - x64
          - x86

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}

      - name: Install packages
        run: npm install --unsafe-perm

      - name: Run configure
        run: npm run configure

      - name: Run install
        run: npm run install

      - name: Run tests
        run: npm test

      - name: Run package
        run: npm run package

      - name: Run publish
        run: set NODE_PRE_GYP_GITHUB_TOKEN=${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }} && npm run publish
